#include "test.h"
#include <parser.h>
#include <ast.h>
#include <fullgen.h>
#include <fullgen-inl.h>

TEST_START(fullgen)
  FULLGEN_TEST("return 1 + 2 + 3\n",
               "0 Label\n"
               "2 Entry\n"
               "4 s[1] = Literal\n"
               "6 s[3] = Literal\n"
               "8 s[4] = Literal\n"
               "10 s[2] = BinOp(s[3], s[4])\n"
               "12 s[0] = BinOp(s[1], s[2])\n"
               "14 s[0] = Return(s[0])\n"
               "16 s[0] = Nil\n"
               "18 Return(s[0])\n")
  FULLGEN_TEST("i = 0\nreturn i\n",
               "0 Label\n"
               "2 Entry\n"
               "4 s[1] = Literal\n"
               "6 Store(s[0], s[1])\n"
               "8 s[1] = Chi(s[1])\n"
               "10 s[1] = Load(s[0])\n"
               "12 s[1] = Return(s[1])\n"
               "14 s[1] = Nil\n"
               "16 Return(s[1])\n")
  FULLGEN_TEST("a = { y: 1 }\na.x = 0\ndelete a.y\nreturn a.x\n",
               "0 Label\n"
               "2 Entry\n"
               "4 s[2] = AllocateObject\n"
               "6 s[3] = Literal\n"
               "8 s[4] = Literal\n"
               "10 StoreProperty(s[2], s[4], s[3])\n"
               "12 s[1] = Chi(s[2])\n"
               "14 Store(s[0], s[1])\n"
               "16 s[1] = Chi(s[1])\n"
               "18 s[1] = Literal\n"
               "20 s[2] = Literal\n"
               "22 s[3] = Load(s[0])\n"
               "24 StoreProperty(s[3], s[2], s[1])\n"
               "26 s[1] = Chi(s[1])\n"
               "28 s[1] = Literal\n"
               "30 s[2] = Load(s[0])\n"
               "32 DeleteProperty(s[2], s[1])\n"
               "34 s[1] = Nil\n"
               "36 s[2] = Literal\n"
               "38 s[3] = Load(s[0])\n"
               "40 s[1] = LoadProperty(s[3], s[2])\n"
               "42 s[1] = Return(s[1])\n"
               "44 s[1] = Nil\n"
               "46 Return(s[1])\n")
  FULLGEN_TEST("return a++\n",
               "0 Label\n"
               "2 Entry\n"
               "4 s[3] = Load(s[0])\n"
               "6 s[4] = Literal\n"
               "8 s[2] = BinOp(s[3], s[4])\n"
               "10 Store(s[0], s[2])\n"
               "12 s[1] = Chi(s[3])\n"
               "14 s[1] = Return(s[1])\n"
               "16 s[1] = Nil\n"
               "18 Return(s[1])\n")
  FULLGEN_TEST("return ++a\n",
               "0 Label\n"
               "2 Entry\n"
               "4 s[3] = Load(s[0])\n"
               "6 s[4] = Literal\n"
               "8 s[2] = BinOp(s[3], s[4])\n"
               "10 Store(s[0], s[2])\n"
               "12 s[1] = Chi(s[2])\n"
               "14 s[1] = Return(s[1])\n"
               "16 s[1] = Nil\n"
               "18 Return(s[1])\n")
  FULLGEN_TEST("return ++a.b\n",
               "0 Label\n"
               "2 Entry\n"
               "4 s[5] = Literal\n"
               "6 s[6] = Load(s[0])\n"
               "8 s[3] = LoadProperty(s[6], s[5])\n"
               "10 s[4] = Literal\n"
               "12 s[2] = BinOp(s[3], s[4])\n"
               "14 StoreProperty(s[6], s[5], s[2])\n"
               "16 s[1] = Chi(s[2])\n"
               "18 s[1] = Return(s[1])\n"
               "20 s[1] = Nil\n"
               "22 Return(s[1])\n")
  FULLGEN_TEST("return +a\n",
               "0 Label\n"
               "2 Entry\n"
               "4 s[2] = Literal\n"
               "6 s[3] = Load(s[0])\n"
               "8 s[1] = BinOp(s[2], s[3])\n"
               "10 s[1] = Return(s[1])\n"
               "12 s[1] = Nil\n"
               "14 Return(s[1])\n")
  FULLGEN_TEST("return clone a\n",
               "0 Label\n"
               "2 Entry\n"
               "4 s[2] = Load(s[0])\n"
               "6 s[1] = Clone(s[2])\n"
               "8 s[1] = Return(s[1])\n"
               "10 s[1] = Nil\n"
               "12 Return(s[1])\n")
  FULLGEN_TEST("if (1) {\na = 1\n} else {\na = 2\n}\nreturn a",
               "0 Label\n"
               "2 Entry\n"
               "4 s[1] = Literal\n"
               "6 If (s[1]) => 8 Else 18\n"
               "8 Label\n"
               "10 s[2] = Literal\n"
               "12 Store(s[0], s[2])\n"
               "14 s[2] = Chi(s[2])\n"
               "16 Goto => 26\n"
               "18 Label\n"
               "20 s[2] = Literal\n"
               "22 Store(s[0], s[2])\n"
               "24 s[2] = Chi(s[2])\n"
               "26 Label\n"
               "28 s[1] = Load(s[0])\n"
               "30 s[1] = Return(s[1])\n"
               "32 s[1] = Nil\n"
               "34 Return(s[1])\n")
  FULLGEN_TEST("while (1) {\nwhile(2) { break }\nbreak\n}",
               "0 Label\n"
               "2 Entry\n"
               "4 Label\n"
               "6 s[0] = Literal\n"
               "8 If (s[0]) => 10 Else 30\n"
               "10 Label\n"
               "12 Label\n"
               "14 s[1] = Literal\n"
               "16 If (s[1]) => 18 Else 24\n"
               "18 Label\n"
               "20 Break => 24\n"
               "22 Goto => 12\n"
               "24 Label\n"
               "26 Break => 30\n"
               "28 Goto => 4\n"
               "30 Label\n"
               "32 s[0] = Nil\n"
               "34 Return(s[0])\n")

  // Functions and arguments
  FULLGEN_TEST("a(x, y..., p) {}",
               "0 Label\n"
               "2 Entry\n"
               "4 s[1] = Function\n"
               "6 Store(s[0], s[1])\n"
               "8 s[1] = Chi(s[1])\n"
               "10 s[1] = Nil\n"
               "12 Return(s[1])\n"
               "14 AlignCode\n"
               "16 Label\n"
               "18 Entry\n"
               "22 s[3] = Literal\n"
               "22 s[3] = Literal\n"
               "24 s[4] = LoadArg(s[3])\n"
               "26 Store(s[0], s[4])\n"
               "28 s[3] = Literal\n"
               "30 s[6] = AllocateArray\n"
               "32 s[5] = Literal\n"
               "34 s[4] = LoadVarArg(s[3], s[5], s[6])\n"
               "36 Store(s[1], s[6])\n"
               "38 s[5] = Sizeof(s[6])\n"
               "40 s[3] = BinOp(s[3], s[5])\n"
               "42 s[4] = LoadArg(s[3])\n"
               "44 Store(s[2], s[4])\n"
               "46 s[3] = Nil\n"
               "48 Return(s[3])\n")

  FULLGEN_TEST("a(x, y..., p)",
               "0 Label\n"
               "2 Entry\n"
               "4 s[4] = Load(s[0])\n"
               "6 s[5] = Load(s[1])\n"
               "8 s[6] = Load(s[2])\n"
               "10 s[7] = Literal\n"
               "12 s[8] = Sizeof(s[5])\n"
               "14 s[7] = BinOp(s[7], s[8])\n"
               "16 s[12] = Load(s[3])\n"
               "18 AlignStack(s[7])\n"
               "20 s[9] = Literal\n"
               "22 s[10] = Literal\n"
               "24 s[10] = BinOp(s[10], s[8])\n"
               "26 s[11] = Literal\n"
               "28 s[10] = BinOp(s[10], s[11])\n"
               "30 s[11] = Literal\n"
               "32 s[11] = BinOp(s[10], s[11])\n"
               "34 StoreArg(s[6], s[11])\n"
               "36 StoreVarArg(s[5], s[10])\n"
               "38 StoreArg(s[4], s[9])\n"
               "40 s[7] = Call(s[12], s[7])\n"
               "42 s[7] = Nil\n"
               "44 Return(s[7])\n")
  // Regression
  FULLGEN_TEST("if (x) x()",
               "0 Label\n"
               "2 Entry\n"
               "4 s[1] = Load(s[0])\n"
               "6 If (s[1]) => 8 Else 22\n"
               "8 Label\n"
               "10 s[2] = Literal\n"
               "12 s[5] = Load(s[0])\n"
               "14 AlignStack(s[2])\n"
               "16 s[4] = Literal\n"
               "18 s[1] = Call(s[5], s[2])\n"
               "20 Goto => 24\n"
               "22 Label\n"
               "24 Label\n"
               "26 s[1] = Nil\n"
               "28 Return(s[1])\n")
TEST_END(fullgen)
