print = global.print
assert = global.assert

print('-- can: arrays --')

// Sizeof
a = [1, 2, 3, 4]
assert(sizeof a == 4, "sizeof")
assert(sizeof [1] == 1, "sizeof [1]")

// Growing
a[4] = 5
assert(sizeof a == 5, "growing")

// Shrinking
a[4] = nil
assert(sizeof a == 4, "shrinking")

// Delete
delete a[3]
assert(sizeof a == 3, "delete")

// Rehashing dense->dense->...->object
i = 100
a = []
while (--i) {
  a[i] = i
}

assert(sizeof a === 100, "array grows through rehashing")

i = 100
while (--i) {
  assert(a[i] === i, "All items are in place:" + i)
}

// Bigger Rehashing dense->dense->...->object
i = 0
a = []
while (++i < 100000) {
  a[i] = i
}

assert(sizeof a === 100000, "array grows through rehashing")
