scope assert, print

// Basic flow and binary ops checks
i = 1000000
while (i--) { }
assert(i == -1, "i-- should decrement")

i = 1000000
while (--i) { }
assert(i == 0, "--i should decrement")

// Arrays
a = keysof { a: 1, b: 2, c: 3 }
i = 0
while (i < sizeof a) {
  scope assert, print, a, i
  assert(a[i] == 'a' || a[i] == 'b' || a[i] == 'c', "keysof")
  i++
}

a = [1,2,3]
assert(a[-1] === nil, "negative index")
a[-1] = 1
assert(a[-1] === 1, "negative index#2")

// Objects
a = { x: 1 , y: 1 }
assert(a.x == 1, "key lookup")
assert(a.y != 2, "key lookup#2")
assert(a.z === nil, "unexisting key lookup")

a.z = 2
assert(a.z == 2, "key lookup#3")
