print = global.print
assert = global.assert

print('-- can: binary --')

assert(1 + 1 === 2, "add")
assert(3 * 2 === 6, "mul")
assert(3.0 * 2 === 6, "mul: heap & smi")
assert(3 * 2.0 === 6, "mul: smi & heap")
assert(3 / 2 === 1.5, "div")
assert(7 % 4 === 3, "mod")
assert(7.0 % 3 === 1, "mod: heap & smi")
assert(7 % 3.0 === 1, "mod: smi & heap")
assert(7 >> 1 === 3, "shr: 1")
assert(7 >> 7 === 0, "shr: 7")
assert(7 << 1 === 14, "shl: 1")
assert(7 << 2 === 28, "shl: 2")
assert(-7 << 1 === -14, "shl: 1, neg")
assert(-7 >> 1 === -4, "shr: 1, neg")

big1 = -7 >>> 1
assert(big1 === 4611686018427387900 || big1 === 1073741820, "big1")

assert(1 != nil, "regr#1")
assert(!(nil == 1), "regr#2")
