print = global.print
assert = global.assert

print('-- can: objects --')

a = { i_am_key: true }

obj = {}
obj[a] = 1

assert(obj[a] == 1, "non-string and non-number key")

keys = keysof obj
assert(sizeof keys == 1, "keysof should work")
assert(keys[0] === a, "key should be the object")

delete obj[a]
assert(obj[a] === nil, "lookup after delete")

// Self-calls
a = {
  x: (self) {
    assert(self.y === 1, "Self calls propogate self")
  },
  y: 1
}

a:x()
